{
 "title": "Pokecord/Catch Activity",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Pokémon Catch Activity by Shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(bot_commands_catch_catches_total[1m])) by (shard)",
     "legendFormat": "Shard {{shard}}"
    }
   ]
  },
  {
   "title": "Pokémon Catch Activity by Guild ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(15, sum(increase(bot_commands_catch_catches_total[1m])) by (guild))",
     "legendFormat": "{{guild}}"
    }
   ]
  },
  {
   "title": "Pokémon Catch Activity by User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "label_join(\n  topk(30, sum(increase(bot_commands_catch_catches_total[1m])) by (user_id, user_tag)),\n  \"user\", \" - \", \"user_tag\", \"user_id\"\n)",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}