{
 "title": "Pokecord/Command Usage Activity",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Command Usage Activity by Shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(bot_commands_usages_total[1m])) by (shard)",
     "legendFormat": "Shard {{shard}}"
    }
   ]
  },
  {
   "title": "Command Usage Activity by Guild ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(bot_commands_usages_total[1m])) by (guild)",
     "legendFormat": "{{guild}}"
    }
   ]
  },
  {
   "title": "Command Usage Activity by Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(bot_commands_usages_total[1m])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Command Usage Activity by User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "label_join(\n  sum(increase(bot_commands_usages_total[1m])) by (user_id, user_tag),\n  \"user_id\", \" - \", \"user_tag\", \"user_id\"\n)",
     "legendFormat": "{{user_id}}"
    }
   ]
  }
 ]
}