{
 "title": "Pokecord/Misc Stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Guild Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "bot_misc_guild_count" }
   ]
  },
  {
   "title": "Registered User Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "bot_misc_user_count" }
   ]
  },
  {
   "title": "Total Credits Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(bot_misc_credits_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Pokémon Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "bot_misc_pokemon_count" }
   ]
  }
 ]
}