{
 "title": "Pokecord/Spawn Activity",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Pokémon Spawn Activity by Shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(bot_spawner_spawns_total[1m])) by (shard)",
     "legendFormat": "Shard {{shard}}"
    }
   ]
  },
  {
   "title": "Pokémon Spawn Activity by Guild ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(15, sum(increase(bot_spawner_spawns_total[1m])) by (guild))",
     "legendFormat": "{{guild}}"
    }
   ]
  },
  {
   "title": "Pokémon Spawn Activity by Channel ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum(increase(bot_spawner_spawns_total[1m])) by (channel))",
     "legendFormat": "{{guild}}"
    }
   ]
  }
 ]
}