name: Docker

on: [push]

jobs:
  test-and-build:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure git
        run: |
          git config --global user.email "pokecord@pokecord.xyz"
          git config --global user.name "Pokecord"
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Docker build
        run: docker build . -t ghcr.io/poke-cord/pokecordjda:latest --cache-from ghcr.io/poke-cord/pokecordjda:latest
      - name: Docker push tag latest
        run: docker push ghcr.io/poke-cord/pokecordjda:latest
        if: github.ref == 'refs/heads/main'
